### ISSUE TITLE
how to change host

### ISSUE THREAD

**Issue by zyf0330** [nparashuram/cordova-plugin-browsersync#18]
I `run android` with `-- -- live-reload`, but address at android still show localhost and thing can't work normally. How to change host ?

**Comment by zyf0330** [comment]
I just saw the video at the home page, and found that you have the extra WIFI address which is a LAN address in `localhost:3001` page. But I don't have it at windows 10 system and run with android target.

**Comment by zyf0330** [comment]
I add `online: true` into options, and the External Address appears. But it is still abnormal on Android. So disappointed.

**Comment by axemclion** [comment]
@zyf0330  I am looking at this during the weekend. Will be working on stabilizing Android, iOS, Browser and Windows.

**Comment by zyf0330** [comment]
OK！

On Fri, May 20, 2016, 12:04 Parashuram N <notifications@github.com> wrote:

> @zyf0330 <https://github.com/zyf0330> I am looking at this during the
> weekend. Will be working on stabilizing Android, iOS, Browser and Windows.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nparashuram/cordova-plugin-browsersync/issues/18#issuecomment-220512455>
>
-- 

追随

**Comment by TombolaShepless** [comment]
@axemclion any word on this?

**Comment by axemclion** [comment]
@TombolaShepless I have not gotten time to work on this. I would appreciate a pull request to get this fixed.

**Comment by zyf0330** [comment]
Sorry, but I cannot help. I am not in it.
