### ISSUE TITLE
Option for https

### ISSUE THREAD

**Issue by MichalKrakow** [nparashuram/cordova-plugin-browsersync#30]
Since there where some changes in policy and some features dont work on insecure origins it would be awesome to have some flag for using secured connection with browsersync server.

Regards.

**Comment by axemclion** [comment]
@MichalKrakow Could you send in a PR for this feature ?

**Comment by patrickbussmann** [comment]
I added a comment because your change breaks all other builds which are not working with https.
But thanks 👍
