### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by masakura** [nparashuram/cordova-plugin-browsersync#41]
The latest release is last year. Several functions have been committed, so I want a new release.

**Comment by axemclion** [comment]
I have added @patrickbussmann as a committer on the project, he has some open PRs. Once those are merged, i will publish it to npm.

**Comment by patrickbussmann** [comment]
@axemclion:

```
git push "origin" refs/heads/master:refs/heads/master
ERROR: Permission to nparashuram/cordova-plugin-browsersync.git denied to patrickbussmann.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done
```

![2017-09-14 10_47_09](https://user-images.githubusercontent.com/15617021/30420533-1dc226ba-993a-11e7-9381-31667a4e28a8.png)

**Comment by axemclion** [comment]
You may have to accept the invite. Shows me that the invitation is still awaiting your response.

**Comment by patrickbussmann** [comment]
Ok thank you @axemclion.
@masakura I created a new version with the new features.

@axemclion maybe you can add the webhook for NPM so that it updates automatically 👍

**Comment by axemclion** [comment]
Done - published a new version.

**Comment by masakura** [comment]
Thanks! @axemclion
