### ISSUE TITLE
Which plugin version to install

### ISSUE THREAD

**Issue by dpreussner** [nparashuram/cordova-plugin-browsersync#45]
Hello,

I noticed some inconsistencies in the versioning of the plugin.

According to this repository the latest version is `0.1.7` but in the npm registry the latest published version is the version `1.1.0` - which one is the correct one? The version `1.1.0` (at least for me) did not work as shown in your video.

It seems like the when running `cordova run browser -- --live-reload` it does start the normal dev sever on port `8000` and the live reload server on port `8002` and `3001`.

From the log:
```
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:8002
    External: http://172.27.218.31:8002
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://172.27.218.31:3001
```
In the end no browser is able to connect and thus live reloading does work...

Thanks in advance

**Comment by patrickbussmann** [comment]
Use 0.1.8 now

If not connecting try my comment here: https://github.com/nparashuram/cordova-plugin-browsersync/issues/31
