### ISSUE TITLE
Support for Windows targets

### ISSUE THREAD

**Issue by pke** [nparashuram/cordova-plugin-browsersync#6]
Does it work with Windows targets?

**Comment by axemclion** [comment]
At the moment, no. Would love a PR supporting Windows though.

**Comment by pke** [comment]
I had hoped at MS work people who would give that a thought ;)
What's so different on the Windows target that it does not work right out of the box?

**Comment by asselin** [comment]
PR submitted

**Comment by axemclion** [comment]
@asselin You mean this PR is for getting live-reload working on a Windows development environment, not for WIndows 10 apps, right ?

**Comment by asselin** [comment]
@axemclion Yes, correct.  Looks like I may have misunderstood this issue; if the issue means that the plugin doesn't work for Windows targets, I haven't tried that at all.  What I've fixed and tested is browsersync for an Android target on Windows.

I think my PR is probably necessary to get a Windows target working, but I don't know if it's sufficient (and haven't tried it).

Sorry for the confusion.

**Comment by axemclion** [comment]
@asselin - that makes sense. I will merge the PR so that this tool works on Windows also

**Comment by axemclion** [comment]
@pke I just checked the support for Windows 10, and looks like it is a little harder than I anticipated. The issue is that you apparently cannot redirect the webview to an external domain without user consent. I was not able to find a way around that. This issue makes the implementation for Windows harder.
