### ISSUE TITLE
Having opts.forEach error

### ISSUE THREAD

**Issue by jgluhov** [nparashuram/cordova-plugin-browsersync#7]
ERROR running one or more of the platforms: TypeError: opts.forEach is not a function
You may not have the required environment or OS to run this project

**Comment by jgluhov** [comment]
Sorry Everything is fine. But I have spent a lot of time to get known how to run your plugin. And I have an success after this command cordova run -- --live-reload --ignore=lib/**/*.*... Command like in your video just cordova run doesn't run browser sync...

**Comment by axemclion** [comment]
I think the video is a little outdated - I have made many changes in the library. Maybe I could document that in the video. is there something in the README that we should change?

**Comment by jgluhov** [comment]
Parashuram could you help me. I'm happy to run your plugin. but now I want
to debug in chrome develper tool my app. May be you recommend me anything
to make my dream come true ?
